[package]
name = "PyMEMOdb"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.4", features = ["extension-module"] }
MEMOdb = { path = "../memodb" }
[lib]
crate-type = ["cdylib"]
